[package]
name = "jm-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "jm"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
jm-core.workspace = true
clap = { version = "4", features = ["derive"] }
